/**
 * Implementation codes, generated from the "Codes" file of the repository.
 * Values are compared after normalisation (see normCode_ in Refresh.gs): lower case,
 * no accents, no tabs, no leading punctuation, single spaces. If no exact match is
 * found for a status, it is compared again with dates removed, so that
 * "Go for delivery (12/03/26)" is read like "Go for delivery".
 * Add new values here when the dashboard reports "Unclassified" solutions.
 */
const CODES = {
  // Column CU left empty: 'open', 'closed' or '' (= unclassified).
  IMPL_STATUS_EMPTY: 'open',

  // Column CL: implementation type.
  IMPL_TYPE_MANUAL: [
    "contract",
    "ds",
    "ecp",
    "ecr",
    "letter/e-mail",
    "mp/ecp1b",
    "mpc",
    "po",
    "qp",
    "qr / qtr",
    "qualification",
    "service bulletin",
    "supplier name",
    "supplier offer",
    "tn"
  ],
  IMPL_TYPE_TOM: [
    "amp",
    "cr",
    "ecp (corepdm)",
    "ecp (sap)",
    "ecp1b",
    "ecp2",
    "ecpf",
    "ecr (corepdm)",
    "ecr (sap)",
    "mp",
    "rnsp",
    "rr",
    "rwsp",
    "te",
    "te (webtek)"
  ],

  // Column CU: implementation status.
  IMPL_STATUS_OPEN: [
    "01 - pending technical check",
    "01 - to be started",
    "01b - pending technical check",
    "01b. pending technical check",
    "05 - workflow launch",
    "06 - wfip: 1 signature",
    "07 - wfip: 2 signatures",
    "08 - wfip: 3 signatures",
    "09 - wfip: 4 signatures",
    "22/06/2026 : technical check",
    "administrative check",
    "airworthiness classification in progress",
    "cg2",
    "cg3",
    "cg31",
    "draft",
    "id created",
    "in progress",
    "in work",
    "jtcb ok, waiting for tls go",
    "ongoing, waiting for descision sheet",
    "open_cg11",
    "open_cg2",
    "pending quality check",
    "pending technical check",
    "pending tehcnical check",
    "quality check",
    "ready for qg1",
    "ready_for_cg11",
    "readyforcg4",
    "rr in progress",
    "signature purchase but issue c awaited",
    "technical check",
    "technical inquiry",
    "technical review",
    "technical_review",
    "tr in progress",
    "under approval",
    "under cb agreement",
    "under change board agreement",
    "under_review_cg11",
    "underreviewcg2",
    "worflow launch",
    "workflow lauch",
    "workflow launch",
    "workflow launched",
    "workflow lunch",
    "workflow reminder",
    "workflow signature",
    "workflow signature (1 signature)",
    "workflow signature : 3 signatures",
    "workflow signature launched"
  ],
  IMPL_STATUS_CLOSED: [
    "02 - refusal at check quality",
    "02 - refusal at quality check",
    "10 - completed",
    "10 - go for delivery",
    "10 completed",
    "10. go for delivery",
    "10.b - go for delivery",
    "10.b -go for delivery",
    "10a - go for delivery",
    "10a - go for development",
    "10a go for development",
    "10a. go for delivery",
    "10a. go for developement",
    "10b - completed",
    "10b - completed (go for delivery)",
    "10b - completed go for delivery",
    "10b - go fo delivery",
    "10b - go for delivery",
    "10b-completed (go for delivery)",
    "10b. go for delivery",
    "11 - cancelled",
    "12 - on hold",
    "1ab. go for delivery",
    "3648995020_01_ah_02",
    "a",
    "accepted",
    "accepted on 04/10/2005.",
    "accepted on 07/11/2011.",
    "accepted on 10/11/2017",
    "accepted on 13/11/2019",
    "accepted on 16/04/2013.",
    "accepted on 20/01/2022",
    "accepted on 20/02/2020.",
    "accepted on 22/04/2021",
    "accepted on 22/11/2006.",
    "accepted on 23/07/2013",
    "accepted on 27/02/2007.",
    "accepted on 29/03/2021.",
    "accepted on 30/06/2005",
    "accepted_cg11",
    "accepted_cg12",
    "acceptedcg3",
    "ahg agreed",
    "approved",
    "b",
    "c",
    "cancelled",
    "cancelled (waiting for update)",
    "cg4",
    "cg5",
    "closed",
    "closed with cr",
    "closed with diu",
    "closed without cr",
    "closed wo cr",
    "closedcg5",
    "completed",
    "completed (go delivery)",
    "completedcg4",
    "ds date 17.01.2023",
    "e",
    "ecpf fournisseur",
    "edited by author / sdr",
    "engineering closed",
    "finalized",
    "for info only",
    "for information only (etso)",
    "g",
    "go delivery",
    "go for del",
    "go for delivery",
    "go for delivery (01/07/25)",
    "go for delivery (10/06/26)",
    "go for delivery (11/02/25)",
    "go for delivery (11/02/26)",
    "go for delivery (11/03/2026)",
    "go for delivery (16/07/26)",
    "go for delivery (17/09/25)",
    "go for delivery (18/11/25)",
    "go for delivery (26/02/24)",
    "go for delivery (26/06/25)",
    "go for delivery (7/11/25)",
    "go for delivery - new issue to remove nrc",
    "go for delivery the 11/03/2026",
    "go for delivery, mpn added",
    "go for delivery.",
    "go for delivey",
    "go for dev",
    "go for developement",
    "go for development",
    "go for development (14/02/26)",
    "go for development (18/02/26)",
    "go for development (20/08/2024)",
    "go for development (29/06/26)",
    "go for development (30/07/26)",
    "go for developmnt",
    "go for developpement",
    "go for developpment",
    "go for devlopment",
    "go_for_delivery",
    "gor for delivery",
    "in progress.thomas becke ah std validation missing",
    "initial",
    "issue f - go for delivery",
    "jtcb approved",
    "link to 47019-00",
    "merge with 5512",
    "merge with 5514",
    "nhi signed",
    "on hold",
    "on hold - waiting for update request data",
    "on hold - waiting supplier signature",
    "on-hold",
    "open_cg0",
    "ready_for_cg12",
    "readyforcg5",
    "realesed",
    "refusal at quality check",
    "refusal at signature",
    "refused",
    "refused (07/11/25)",
    "refused at quality check",
    "rejected",
    "released",
    "released 09/03/2018",
    "released on 12/10/2022",
    "released on 13/11/2019",
    "released on 21/11/2007",
    "replaced",
    "replacement of u183 74lvc27pw (philips)",
    "rr accepted on 27/07/2021.",
    "rr released on 17/11/2008",
    "signature purchase",
    "signature purchase (25/08/25)",
    "signed",
    "signed ah",
    "signed and go for delivery 21/01/21",
    "signed and released",
    "signed as go for delivery",
    "signed go for delivery",
    "signed go for development",
    "superseded",
    "supplier ref",
    "tcb",
    "to be started",
    "tso / for info only",
    "under validation",
    "validated",
    "wfip",
    "withdrawn"
  ]
};
